config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

   root 'users#index'

   get '/login' => 'sessions#new'
   post '/login' => 'sessions#create', as: 'create_session'
   delete '/logout' => 'sessions#destroy', as: 'logout'

   resources :users do
    resources :categories
   end

   resources :cards

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :categories
  has_many :cards

  validates :username, :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all # set this to only one user's cards
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to card_path(@card)
    else
      render 'new'
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to card_path(@card)
    else
      render 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
  end

  private
  def card_category
    Category.find(@card.category_id)
  end

  def card_user
    User.find(card_category.id)
  end

  def card_params
    params.require(:card).permit(:title, :body, :notes)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @categories = Category.where(user_id: @user.id)
  end

  def new
    @user = User.find(params[:user_id])
    @category = Category.new
  end

  def show
    @user = User.find(params[:user_id])
    @category = Category.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
    @category = @user.categories.new(category_params)

    if @category.save
      redirect_to user_category_path(@user, @category)
    else
      render 'new'
    end
  end

  def edit
    # validate user
    @category = Category.find(params[:id])
  end

  def update
    # validate user
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to user_category_path(@user, @category)
    else
      render 'edit'
    end
  end

  def destroy
    # validate user
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to user_categories_path
  end

  private

  def current_user
    User.find(params[:user_id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :first_name, :last_name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_for @card do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :body %>
  <%= f.text_area :body %><br>
  <%= f.label :notes %>
  <%= f.text_area :notes %><br>
  <%= f.submit %>
<% end %>

app/views/cards/index.html.erb
<% @cards.each do |card| %>
  <p>

  </p>
<% end %>

app/views/cards/new.html.erb
<p>Add a Card</p>

<%= render 'form' %>

app/views/categories/_form.html.erb
<%= form_for([@user, @user.categories.build]) do |f| %>
  <%= f.label "Category Name" %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<% render 'form' %>

<% link_to 'Back', user_category_path(@category) %>

app/views/categories/index.html.erb
<h1><%= @user.first_name %>'s Categories:</h1>

<% @categories.each do |category| %>

<p><%= link_to category.name, user_category_path(@user, category) %></p>

<% end %>

<%= link_to 'Add New Category', new_user_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', user_categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= link_to 'Delete', user_category_path(@user, @category), method: :delete, data: { confirm: "Delete #{@category.name}?" } %><br>
<%= link_to @user.username, user_categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :password %>
  <%= f.text_field :password %><br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<p>Edit User</p>

<%= render 'form' %>

<p><%= link_to 'Back to Users', users_path %></p>
<p><%= link_to 'Delete this User', user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete #{@user.username} from the database?"}  %></p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% @users.each do |user| %>
  <p><%= link_to user.username, user_path(user) %></p>
<% end %>

<%= link_to 'Create New User', new_user_path %>

app/views/users/new.html.erb
<p>Add New User</p>

<%= render 'form' %>

<p><%= link_to 'Back to Users', users_path %></p>

app/views/users/show.html.erb
 <h1>User Info:</h1>
<%= @user.username %><br>
<%= @user.password %><br>
<%= @user.first_name %><br>
<%= @user.last_name %><br>
<%= @user.email %><br>

<p><%= link_to 'Back to Users', users_path %></p>
<p><%= link_to 'Edit this User', edit_user_path(@user) %></p>
<p><%= link_to 'Delete this User', user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete #{@user.username} from the database?"}  %></p>